const sample={Admin:[['🏫','Kelola Kelas','Data kelas dan siswa'],['📚','Mata Pelajaran','Manajemen mapel'],['👥','Guru & Siswa','Akun dan akses'],['📝','Ulangan','Status dan jadwal'],['📊','Laporan Nilai','Download rekapan']],Guru:[['🏫','Kelas Saya','Kelas yang diajar'],['🔗','Link Google Forms','Per kelas dan mapel'],['⏳','Status Pengerjaan','Sudah/belum mengerjakan'],['✅','Nilai','Nilai PG dan essay'],['⬇️','Download Rekap','Excel / CSV']],Siswa:[['📝','Ulangan Tersedia','Daftar soal dan jadwal'],['🏆','Nilai Saya','Lihat hasil ulangan'],['🕘','Riwayat Ulangan','Riwayat pengerjaan'],['👤','Profil','Data siswa']]};
const links=[['IX-A','Matematika','Aktif','https://forms.gle/contoh-matematika'],['VIII-B','IPA','Aktif','https://forms.gle/contoh-ipa'],['VII-A','Bahasa Indonesia','Draft','https://forms.gle/contoh-indonesia']];
const statuses=[['Andi Pratama','IX-A','Matematika','Sudah mengerjakan','86'],['Budi Santoso','IX-A','Matematika','Belum mengerjakan','-'],['Citra Dewi','IX-A','Matematika','Sudah mengerjakan','92']];
let role='Admin';
function login(){role=document.querySelector('#role').value;document.querySelector('#app').innerHTML=dashboard()}
function dashboard(){return `<header class="top"><h2>🎓 SMPN5TSG</h2><button class="btn secondary" onclick="location.reload()">Keluar</button></header><main class="wrap"><div class="welcome"><div><p class="muted">Sistem Ulangan Online</p><h1>Selamat datang, ${role}</h1></div><span class="badge ok">Prototype aktif</span></div><div class="grid">${sample[role].map((x,i)=>`<div class="tile" onclick="openMenu('${x[1]}')"><div class="icon">${x[0]}</div><h3>${x[1]}</h3><p class="muted">${x[2]}</p></div>`).join('')}</div><section class="section"><div class="card"><h2>Ringkasan</h2><div class="grid"><div><b>3</b><p class="muted">Kelas contoh</p></div><div><b>3</b><p class="muted">Mata pelajaran</p></div><div><b>2</b><p class="muted">Sudah mengerjakan</p></div><div><b>86</b><p class="muted">Rata-rata nilai</p></div></div></div></section></main>`}
function openMenu(name){if(name.includes('Google Forms')||name==='Link Google Forms'){document.querySelector('#app').innerHTML=page('Link Google Forms',`<div class="card"><h2>Masukkan link Google Forms</h2><p class="muted">Pilih kelas dan mata pelajaran, lalu tempel link Google Forms.</p><select><option>IX-A</option><option>VIII-B</option><option>VII-A</option></select><select><option>Matematika</option><option>IPA</option><option>Bahasa Indonesia</option></select><input placeholder="https://forms.gle/..."/><button class="btn primary" onclick="alert('Link tersimpan pada prototype.')">Simpan Link</button></div>${links.map(x=>`<div class="card"><b>${x[0]} • ${x[1]}</b><span class="badge ${x[2]==='Aktif'?'ok':'wait'}">${x[2]}</span><p class="muted">${x[3]}</p></div>`).join('')}`)}else if(name.includes('Status')||name==='Nilai'||name.includes('Download')){document.querySelector('#app').innerHTML=page('Status dan Rekap Nilai',`<div class="table-wrap"><table class="table"><tr><th>Nama</th><th>Kelas</th><th>Mapel</th><th>Status</th><th>Nilai</th></tr>${statuses.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td><td><span class="badge ${x[3][0]==='S'?'ok':'wait'}">${x[3]}</span></td><td>${x[4]}</td></tr>`).join('')}</table></div><button class="btn primary" onclick="alert('Fitur download Excel tersedia setelah database dihubungkan.')">⬇️ Download Rekap</button>`)}else{document.querySelector('#app').innerHTML=page(name,`<div class="card"><h2>${name}</h2><p>Menu ini sudah disiapkan dan akan dihubungkan ke database pada tahap berikutnya.</p></div>`)}}
function page(title,content){return `<header class="top"><h2>🎓 SMPN5TSG</h2><button class="btn secondary" onclick="document.querySelector('#app').innerHTML=dashboard()">Dashboard</button></header><main class="wrap"><button class="btn secondary back" onclick="document.querySelector('#app').innerHTML=dashboard()">← Kembali</button><h1>${title}</h1>${content}</main>`}
function start(){document.querySelector('#app').innerHTML=`<main class="login"><section class="card login-card"><div class="logo">S</div><h1>SMPN5TSG</h1><p class="muted">Sistem Ulangan Online</p><label class="field">Email atau akun Google</label><input placeholder="contoh@belajar.id"/><label class="field">Masuk sebagai</label><select id="role"><option>Admin</option><option>Guru</option><option>Siswa</option></select><button class="btn primary" onclick="login()">Masuk ke Aplikasi</button><p class="muted">Versi awal • Akun Google akan dihubungkan pada tahap integrasi</p></section></main>`}start();
